name: expanse_tracker
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  intl: ^0.20.2
  flutter_svg: ^2.1.0
  fl_chart: ^1.0.0
  flutter_launcher_icons: ^0.14.3
  flex_color_picker: ^3.7.1
  shared_preferences: ^2.5.3
  percent_indicator: ^4.2.5
  carousel_slider: ^5.0.0
  flutter_local_notifications: ^19.0.0
  msix: ^3.16.9
  window_manager: ^0.5.0
  tray_manager: ^0.5.0
  timezone: ^0.10.1
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/svg/
    - assets/gif/
    - assets/png/
    - assets/ico/
    - assets/json/
  fonts:
    - family: Kantumruy
      fonts:
        - asset: assets/fonts/KantumruyPro.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png/App Icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/png/App Icon.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/png/App Icon.png"
    background_color: "#2196F3"
    theme_color: "#21CBF3"
  windows:
    generate: true
    image_path: "assets/png/App Icon.png"
    icon_size: 256

msix_config:
  display_name: Expense Tracker
  publisher_display_name: ANT
  identity_name: com.ant.expanse-tracker
  msix_version: 1.0.0.0
  logo_path: assets/png/App Icon.png
  capabilities: internetClient, location, microphone, webcam
  certificate_path: C:\Users\Admin\CERTIFICATE.pfx
  certificate_password: YourStrongPassword123
  publisher: CN=Taing ChingSong

flutter_native_splash:
  color: "#67bb6a"
  image: assets/png/Splash Icon.png
  branding: assets/png/Splash Icon.png
  color_dark: "#121212"
  image_dark: assets/png/Splash Icon.png
  branding_dark: assets/png/Splash Icon.png

  android_12:
    image: assets/png/Splash Icon.png
    icon_background_color: "#67bb6a"
    image_dark: assets/png/Splash Icon.png
    icon_background_color_dark: "#121212"

  web: false
